import '../styles/globals.css'
import {Inter} from 'next/font/google'
import React from "react";
import {QueryClient} from "react-query";
import {ReactQueryProvider} from "@/app/QueryClientProvider";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <ReactQueryProvider>
            <html lang="en">
            <body className={inter.className}>{children}</body>
            </html>
        </ReactQueryProvider>
    )
}
